from setuptools import setup, find_packages

setup(
    name="alphaholdem",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=1.9.0",
        "pyyaml>=5.4.0",
        "wandb>=0.15.0",
        "hydra-core>=1.3.0",
        "omegaconf>=2.3.0",
    ],
    extras_require={
        "dev": [
            "black>=22.0.0",
            "pre-commit>=3.0.0",
            "pytest>=7.0.0",
            "line-profiler>=4.0.0",
        ],
        "all": [
            "black>=22.0.0",
            "pre-commit>=3.0.0",
            "pytest>=7.0.0",
            "wandb>=0.15.0",
            "line-profiler>=4.0.0",
            "hydra-core>=1.3.0",
            "omegaconf>=2.3.0",
        ],
    },
    python_requires=">=3.8",
    description="AlphaHoldem: Deep Reinforcement Learning for Texas Hold'em Poker",
    long_description=open("README.md").read() if open("README.md").readable() else "",
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/poker2",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Games/Entertainment",
    ],
)
