from __future__ import annotations


TARGET_SOURCE_CFR_BACKUP = 0
TARGET_SOURCE_CHANCE_EXPECTATION = 1
TARGET_SOURCE_EXACT_TERMINAL = 2
TARGET_SOURCE_CLOSING_NET = 3


TARGET_SOURCE_NAMES = {
    TARGET_SOURCE_CFR_BACKUP: "cfr_backup",
    TARGET_SOURCE_CHANCE_EXPECTATION: "chance_expectation",
    TARGET_SOURCE_EXACT_TERMINAL: "terminal_exact",
    TARGET_SOURCE_CLOSING_NET: "closing_net",
}
